import Head from 'next/head';
import Navbar from '../../components/all/Navbar/Navbar';

const Envoi = () => {
  return (
    <>
      <Head>
        <title>Envoi | Cardly</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar current="envoi"></Navbar>
      </main>
    </>
  );
};

export default Envoi;
