import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import Navbar from '../../components/all/Navbar/Navbar';
import EnvoiLayout from '../../components/envoi/EnvoiLayout/EnvoiLayout';

const Envoi = () => {
  return (
    <>
      <Head>
        <title>Envoi | Cardly</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1 maximum-scale-1"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* <div className="flex justify-center items-center w-full h-[100px] bg-darkGrey">
          <Link href="/">
            <Image
              src="/assets/logo/logo.svg"
              width={95}
              height={41}
              alt="logo"
            />
          </Link>
        </div> */}
        <EnvoiLayout />
      </main>
    </>
  );
};

export default Envoi;
